_BASE_: "./sseg.yaml"
DATASETS:
  # 781 images (88 + 94 + 599)
  TRAIN: ("wgisd_train", "target_train")
SOLVER:
  MAX_ITER: 78100  # train for 100 epochs
  CHECKPOINT_PERIOD: 781  # checkpoint every epoch
  ITERS_PER_EPOCH: 781
TEST:
  EVAL_PERIOD: 781  # evaluate every epoch
OUTPUT_DIR: "./output/target_segmentator"
SEED: 42
PSEUDOMASKS:
  ENABLED: True
  DATASET_NAME: ["target_train"]
  DATA_FOLDER: ["./datasets/target_dataset/train"]
  PSEUDOMASKS_FOLDER: ["./pseudomasks/target_train"]
  EXTENSION: ["jpg"]
  PROCESS_METHOD: "grabcut"
  MODEL_WEIGHTS: "./output/wgisd_R101/best_model.pth"
  GRABCUT:
    MEDIAN_BLUR: 0
  SLIC:
    SLIC_ZERO: False
    N_SEGMENTS: 2000
    COMPACTNESS: 0.1
    SIGMA: 0
    THRESHOLD: 0.7